version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    networks:
      - ada-2-js

  worker:
    build:
      context: .
    entrypoint: [ "node", "./worker.js" ]
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ada-2-js

networks:
  ada-2-js:
    name: ada-2-js
